name: BusGo EKS CD

on:
  workflow_run:
    workflows: ["Bus Booking CI"]
    types:
      - completed
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  AWS_ACCOUNT_ID: "633398616799"
  ECR_REGISTRY: "633398616799.dkr.ecr.ap-south-1.amazonaws.com"
  ECR_BACKEND: "busgo-backend"
  ECR_FRONTEND: "busgo-frontend"
  EKS_CLUSTER: "busgo-eks"

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::633398616799:role/GitHubActions-BusGo-EKS
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push backend image
        run: |
          docker build \
            -t $ECR_REGISTRY/$ECR_BACKEND:${{ github.event.workflow_run.head_sha }} \
            ./server

          docker push \
            $ECR_REGISTRY/$ECR_BACKEND:${{ github.event.workflow_run.head_sha }}

      - name: Build and push frontend image
        run: |
          docker build \
            --build-arg VITE_API_URL="http://aa64b3e7b078042eaaaf05c0bd78d2de-1712105078.ap-south-1.elb.amazonaws.com:5000" \
            -t $ECR_REGISTRY/$ECR_FRONTEND:${{ github.event.workflow_run.head_sha }} \
            ./client

          docker push \
            $ECR_REGISTRY/$ECR_FRONTEND:${{ github.event.workflow_run.head_sha }}

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $EKS_CLUSTER

      - name: Deploy backend to EKS
        run: |
          kubectl set image deployment/busgo-backend \
            backend=$ECR_REGISTRY/$ECR_BACKEND:${{ github.event.workflow_run.head_sha }}

          kubectl rollout status deployment/busgo-backend --timeout=180s

      - name: Deploy frontend to EKS
        run: |
          kubectl set image deployment/busgo-frontend \
            frontend=$ECR_REGISTRY/$ECR_FRONTEND:${{ github.event.workflow_run.head_sha }}

          kubectl rollout status deployment/busgo-frontend --timeout=180s

      - name: Verify deployment
        run: |
          kubectl get pods
          kubectl get svc busgo-backend
          kubectl get svc busgo-frontend